apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: tsacrpoc.azurecr.io/hellocontainer:1.2
          imagePullPolicy: Always
          name: frontend
          ports:
            - name: frontend
              containerPort: 80
      imagePullSecrets:
        - name: acr-secret
